import {MobileData} from "../src/utils/formatter";
const data3:Array<MobileData>=
[
 {
    id:0,
    primaryColor:"#BE0A1F",
    textColor:'#FFF',
    isRecommended:true,
    buttonColor:'#FFF',
    buttonTextColor:'#000',
    subscriptionName:"Digital + Print + E-paper + Mail",
    discount:"50",
    benefitColor:'#FFF',
    buttonPlaceholder:"Subscribe Now",
    finalPrice:"450",
    benefits:[
    "Access all digital features",
    "Doorstep delievery of print edition",
    "Access to outlook archives",
    "Exclusive eBooks written by our journalists for general knowledge",
    "Access to outlook archives",   
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]  
},   
 {
    id:1,
    primaryColor:'#FFF',
    secondaryColor:"#FFF",
    buttonColor:'#000',
    isRecommended:false,
    buttonTextColor:'#FFF',
    textColor:'#000',
    benefitColor:'#706C6E',
    subscriptionName:"Digital + Print",
    originalPrice:"1200",
    discount:"30",
    buttonPlaceholder:"Subscribe Now",
    finalPrice:"840",
    benefits:[
    "Access All Digital Features",
    "Doorstep delievery of print edition",
    "Access to outlook archives", 
    "Exclusive eBooks written by our journalists",
    "Access to outlook archives",  
    ],
  tiers:[{time:"1 year",price:"800",_id:0} ,{time:'2 year',price:"1500",_id:1},{time:'3 year',price:"3750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:2,
    primaryColor:"#FFF",
    benefitColor:'#706C6E',
    textColor:'#000',
    buttonColor:'#000',
    isRecommended:false,
    buttonTextColor:'#FFF',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
   buttonPlaceholder:"Subscribe Now",
   finalPrice:"450",
   benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives", 
  "Exclusive eBooks written by our journalists",
    "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:3,
    primaryColor:"#FFF",
    benefitColor:"#706C6E",
    textColor:'#000',
    buttonTextColor:'#FFF',
    buttonColor:'#160B09',
    isRecommended:false,
    secondaryColor:'#000',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Exclusive eBooks written by our journalists",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"34400",_id:0} ,{time:'2 year',price:"67500",_id:1}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:4,
    primaryColor:"#FFF",
    benefitColor:"#706C6E",
    textColor:'#000',
    isRecommended:false,
    buttonColor:'#160B09',
    buttonTextColor:'#FFF',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  "Doorstep delievery of print edition",
  "Access to outlook archives",

  ],
  tiers:
  [{time:"1 year",price:"3300",_id:0} ,{time:'2 year',price:"5200",_id:1},{time:'3 year',price:"7503",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:5,
    primaryColor:"#BE0A1F",
    textColor:'#FFF',
    buttonColor:'#FFF',
    isRecommended:true,
    buttonTextColor:'#000',
    subscriptionName:"Digital + Print + E-paper + Mail",
    discount:"50",
    benefitColor:'#FFF',
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"4350",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Exclusive eBooks written by our journalists",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"3100",_id:0} ,{time:'2 year',price:"3500",_id:1},{time:'3 year',price:"1750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ] 
},   
]
export default data3;