import {MobileData} from "../src/utils/formatter";
const data2:Array<MobileData>=
[
 {
    id:0,
    primaryColor:"#0A083E",
    benefitColor:"#FFF",
    isRecommended:true,
    textColor:'#FFF',
    buttonColor:'#E73E88',
    buttonTextColor:'#F9E1F8',
    subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"430",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ] 
 },   
 {
    id:1,
    primaryColor:"#FFF",
    textColor:'#0A083E',
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
    isRecommended:false,
    benefitColor:"#0A083E",
    subscriptionName:"Digital + Print",
    originalPrice:"1200",
    discount:"30",
    buttonPlaceholder:"Subscribe Now",
    finalPrice:"230",
    benefits:[
    "Access All Digital Features",
    "Doorstep delievery of print edition",
    "Access to outlook archives", 
    "Access to outlook archives",  
    "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
 },   
 {
    id:2,
    primaryColor:"#FFF",
    textColor:'#000',
    benefitColor:"#0A083E",
    isRecommended:false,
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"41120",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Access to outlook archives",  
  "Access to outlook archives",   
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
 },   
 {
    id:3,
    primaryColor:"#FFF",
    textColor:'#000',
    isRecommended:false,
    benefitColor:"#0A083E",
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"4523230",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  "Doorstep delievery of print edition",
  "Access to outlook archives",    
],
  tiers:[{time:"1 year",price:"300",_id:0}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ] 
},   
 {
    id:4,
    primaryColor:"#0A083E",
    benefitColor:"#FFF",
    isRecommended:true,
    textColor:'#FFF',
    buttonColor:'#E73E88',
    buttonTextColor:'#F9E1F8',
   subscriptionName:"Digital + Print",
   originalPrice:"978",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Access to outlook archives",  
  "Access to outlook archives",   
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
 },   
 {
    id:5,
    primaryColor:"#FFF",
    textColor:'#000',
    benefitColor:"#0A083E",
    isRecommended:false,
    buttonColor:"#FAF2F7",
    buttonTextColor:'#E73E88',
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
  buttonPlaceholder:"Subscribe Now",
  finalPrice:"450",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives", 
  "Access to outlook archives",  
  "Access to outlook archives",  
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
 },   
]
export default data2;