import {MobileData} from "../src/utils/formatter";
const mobiledata4:MobileData[]=
[{
    id:0,
    primaryColor:"#333333",
    secondaryColor:'#5CA4EE',
    isRecommended:true,
    textColor:'#FFF',
    buttonColor:'#FFFFFF',
    buttonTextColor:'#B7091D',
    subscriptionName:"Digital + Print",
    originalPrice:"900",
    discount:"50",
    benefitColor:'#FFF',
    buttonPlaceholder:"SUBSCRIBE NOW",
  finalPrice:"350",
  benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",
  "Doorstep delievery of print edition",
  "Access to outlook archives",      
  ],
  tiers:
  [{time:"1 year",price:"300",_id:0}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
 },   
 {
    id:1,
    isRecommended:false,
    primaryColor:'#333333',
    secondaryColor:'#FFF',
    textColor:'#FFF',
    originalPrice:"900",
    buttonColor:'#FFFFFF',
    buttonTextColor:'#B7091D',
    discount:"50",
    benefitColor:'#FFF',
   subscriptionName:"DIGITAL + PRINT",
   buttonPlaceholder:"SUBSCRIBE NOW",
   finalPrice:"210",
   benefits:[
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  "Access to outlook archives",  
  "Access All Digital Features",
  "Doorstep delievery of print edition",
  ],
  tiers:
  [{time:"1 year",price:"3340",_id:0} ,{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}],
  offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
},   
 {
    id:2,
    primaryColor:"#333333",
    secondaryColor:'#FFF',
    textColor:'#FFF',
    benefitColor:'#FFF',
    finalPrice:"2450",
    buttonColor:'#FFFFFF',
    buttonTextColor:'#B7091D',
    isRecommended:false,
   subscriptionName:"Digital + Print",
   originalPrice:"900",
   discount:"50",
   buttonPlaceholder:"SUBSCRIBE NOW",
   benefits:[
   "Access All Digital Features",
   "Doorstep delievery of print edition",
   "Access to outlook archives",  
   "Access to outlook archives",  
   "Access All Digital Features",
],
 tiers:[{time:"1 year",price:"3340",_id:0},{time:'2 year',price:"500",_id:1},{time:'3 year',price:"750",_id:2}], 
 offers:
  [
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
    {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
   {iconUrl:'https://play-lh.googleusercontent.com/F8GhJVX4u3O-D3_lV3wi9Xf_NOEB3hdOpSS6626F1xl9Gl1CI2BF5BA9NdeJ4b0FgsDW',
    offerText:'Flat 10% off up to Rs.1000 on flights-No minimum booking amount',
   },
  ]
 },   
];
export default mobiledata4;